# Using Numpy and Pandas

In [100]:
import numpy as np
import pandas as pd

In [101]:
# we can use Pandas to grab eternal data
# this may be a relative address, or an absolute address or a URL
sp500 = pd.read_csv('StockData/sp500.csv')
# sp500 = pd.read_csv('https://raw.githubusercontent.com/onionmccabbage/pythonWeds2026/refs/heads/main/StockData/SP500.csv')
sp500 # We have a Pandas DataFrame

,Date,Open,High,Low,Close,Adj Close,Volume
0,9/30/13,1687.260010,1687.260010,1674.989990,1681.550049,1681.550049,3308630000
1,10/01/13,1682.410034,1696.550049,1682.069946,1695.000000,1695.000000,3238690000
2,10/02/13,1691.900024,1693.869995,1680.339966,1693.869995,1693.869995,3148600000
3,10/03/13,1692.349976,1692.349976,1670.359985,1678.660034,1678.660034,3279650000
4,10/04/13,1678.790039,1691.939941,1677.329956,1690.500000,1690.500000,2880270000
...,...,...,...,...,...,...,...
1255,9/24/18,2921.830078,2923.790039,2912.629883,2919.370117,2919.370117,3372210000
1256,9/25/18,2921.750000,2923.949951,2913.699951,2915.560059,2915.560059,3285480000
1257,9/26/18,2916.979980,2931.149902,2903.280029,2905.969971,2905.969971,3388620000
1258,9/27/18,2911.649902,2927.219971,2909.270020,2914.000000,2914.000000,3060850000
1259,9/28/18,2910.030029,2920.530029,2907.500000,2913.979980,2913.979980,3432300000

In [102]:
# Numpy and Arrays
f = np.random.normal(10, 3, 8) # pick n numbers from the set of numbers average 10 sd 3

In [103]:
f.sum()
f.mean() # max() min()
f.max()
np.std(f)
# we may need to show several values at once
f'sum: {f.sum()} max/min {f.max()}/{f.min()}'

'sum: 91.18154768518377 max/min 15.554943689931166/5.508876825328692'

In [104]:
# Pandas Data Frame
# we can grab data using reaad_csv or read_excel etc
sp500 = pd.read_csv('StockData/sp500.csv')
sp500['Date'] # we may need to convert strings to actual dates
sp500['Date'] = pd.to_datetime( sp500['Date'] , format='%m/%d/%y') # a date-time picture

In [105]:
sp500['Date']
sp500

,Date,Open,High,Low,Close,Adj Close,Volume
0,2013-09-30,1687.260010,1687.260010,1674.989990,1681.550049,1681.550049,3308630000
1,2013-10-01,1682.410034,1696.550049,1682.069946,1695.000000,1695.000000,3238690000
2,2013-10-02,1691.900024,1693.869995,1680.339966,1693.869995,1693.869995,3148600000
3,2013-10-03,1692.349976,1692.349976,1670.359985,1678.660034,1678.660034,3279650000
4,2013-10-04,1678.790039,1691.939941,1677.329956,1690.500000,1690.500000,2880270000
...,...,...,...,...,...,...,...
1255,2018-09-24,2921.830078,2923.790039,2912.629883,2919.370117,2919.370117,3372210000
1256,2018-09-25,2921.750000,2923.949951,2913.699951,2915.560059,2915.560059,3285480000
1257,2018-09-26,2916.979980,2931.149902,2903.280029,2905.969971,2905.969971,3388620000
1258,2018-09-27,2911.649902,2927.219971,2909.270020,2914.000000,2914.000000,3060850000
1259,2018-09-28,2910.030029,2920.530029,2907.500000,2913.979980,2913.979980,3432300000

In [106]:
# we may wish to store our prepared data
sp500.to_excel('StockData/sp500_clean.xlsx')

In [112]:
# make the index based on the 'Date' column
sp500.set_index( 'Date', inplace=True ) # we specify the column as the index (column gets removed)

In [113]:
sp500

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2013-09-30,1687.260010,1687.260010,1674.989990,1681.550049,1681.550049,3308630000
2013-10-01,1682.410034,1696.550049,1682.069946,1695.000000,1695.000000,3238690000
2013-10-02,1691.900024,1693.869995,1680.339966,1693.869995,1693.869995,3148600000
2013-10-03,1692.349976,1692.349976,1670.359985,1678.660034,1678.660034,3279650000
2013-10-04,1678.790039,1691.939941,1677.329956,1690.500000,1690.500000,2880270000
...,...,...,...,...,...,...
2018-09-24,2921.830078,2923.790039,2912.629883,2919.370117,2919.370117,3372210000
2018-09-25,2921.750000,2923.949951,2913.699951,2915.560059,2915.560059,3285480000
2018-09-26,2916.979980,2931.149902,2903.280029,2905.969971,2905.969971,3388620000
2018-09-27,2911.649902,2927.219971,2909.270020,2914.000000,2914.000000,3060850000
2018-09-28,2910.030029,2920.530029,2907.500000,2913.979980,2913.979980,3432300000

In [117]:
# slicing
sp500.loc['20130930':'20131007'] # start:stop INCLUSIVE

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2013-09-30,1687.260010,1687.260010,1674.989990,1681.550049,1681.550049,3308630000
2013-10-01,1682.410034,1696.550049,1682.069946,1695.000000,1695.000000,3238690000
2013-10-02,1691.900024,1693.869995,1680.339966,1693.869995,1693.869995,3148600000
2013-10-03,1692.349976,1692.349976,1670.359985,1678.660034,1678.660034,3279650000
2013-10-04,1678.790039,1691.939941,1677.329956,1690.500000,1690.500000,2880270000
2013-10-07,1687.150024,1687.150024,1674.699951,1676.119995,1676.119995,2678490000

In [120]:
# we may also use the underlying ordinal index with iloc
sp500.iloc[15:18] # we're back to start:stop-before

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2013-10-21,1745.199951,1747.790039,1740.670044,1744.660034,1744.660034,3052710000
2013-10-22,1746.479980,1759.329956,1746.479980,1754.670044,1754.670044,3850840000
2013-10-23,1752.270020,1752.270020,1740.500000,1746.380005,1746.380005,3713380000

In [124]:
# we may also choose which columns we wish to see
sp500['Volume'] # for a single column, just use []
sp500[['Volume', 'High']] # for more than one column use [[]] ( the inner [] is a list )

                Volume         High
Date
2013-09-30  3308630000  1687.260010
2013-10-01  3238690000  1696.550049
2013-10-02  3148600000  1693.869995
2013-10-03  3279650000  1692.349976
2013-10-04  2880270000  1691.939941
...                ...          ...
2018-09-24  3372210000  2923.790039
2018-09-25  3285480000  2923.949951
2018-09-26  3388620000  2931.149902
2018-09-27  3060850000  2927.219971
2018-09-28  3432300000  2920.530029

[1260 rows x 2 columns]

In [125]:
# how could we show just October 2013 only Open and Close
sp500.loc['20131001':'20131031'][['Open', 'Close']]

                   Open        Close
Date
2013-10-01  1682.410034  1695.000000
2013-10-02  1691.900024  1693.869995
2013-10-03  1692.349976  1678.660034
2013-10-04  1678.790039  1690.500000
2013-10-07  1687.150024  1676.119995
2013-10-08  1676.219971  1655.449951
2013-10-09  1656.989990  1656.400024
2013-10-10  1660.880005  1692.560059
2013-10-11  1691.089966  1703.199951
2013-10-14  1699.859985  1710.140015
2013-10-15  1709.170044  1698.060059
2013-10-16  1700.489990  1721.540039
2013-10-17  1720.170044  1733.150024
2013-10-18  1736.719971  1744.500000
2013-10-21  1745.199951  1744.660034
2013-10-22  1746.479980  1754.670044
2013-10-23  1752.270020  1746.380005
2013-10-24  1747.479980  1752.069946
2013-10-25  1756.010010  1759.770020
2013-10-28  1759.420044  1762.109985
2013-10-29  1762.930054  1771.949951
2013-10-30  1772.270020  1763.310059
2013-10-31  1763.239990  1756.540039

In [131]:
# we may apply operations to our data
sp500['Volume'].sum()
sp500['Volume'].mean()
sp500.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 1260 entries, 2013-09-30 to 2018-09-28
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Open       1260 non-null   float64
 1   High       1260 non-null   float64
 2   Low        1260 non-null   float64
 3   Close      1260 non-null   float64
 4   Adj Close  1260 non-null   float64
 5   Volume     1260 non-null   int64
dtypes: float64(5), int64(1)
memory usage: 101.2 KB

In [133]:
sp500.describe()

,Open,High,Low,Close,Adj Close,Volume
count,1260.000000,1260.000000,1260.000000,1260.000000,1260.000000,1.260000e+03
mean,2208.119022,2217.222041,2198.329731,2208.579183,2208.579183,3.545683e+09
std,311.783587,312.018261,311.768926,311.699505,311.699505,6.785854e+08
min,1656.989990,1662.469971,1646.469971,1655.449951,1655.449951,1.307630e+09
25%,1984.504975,1991.565002,1975.112457,1985.515015,1985.515015,3.154532e+09
50%,2101.550049,2108.744995,2091.594971,2101.265014,2101.265014,3.448470e+09
75%,2434.364991,2441.522522,2428.234985,2434.777527,2434.777527,3.821982e+09
max,2936.760010,2940.909912,2927.110107,2930.750000,2930.750000,7.597450e+09

In [140]:
# sort, filter, moving average
sp500.sort_values(['Volume', 'Close'], ascending=False) # sort by one or more columns
sp500 # we may choose to include inplace=True

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2013-09-30,1687.260010,1687.260010,1674.989990,1681.550049,1681.550049,3308630000
2013-10-01,1682.410034,1696.550049,1682.069946,1695.000000,1695.000000,3238690000
2013-10-02,1691.900024,1693.869995,1680.339966,1693.869995,1693.869995,3148600000
2013-10-03,1692.349976,1692.349976,1670.359985,1678.660034,1678.660034,3279650000
2013-10-04,1678.790039,1691.939941,1677.329956,1690.500000,1690.500000,2880270000
...,...,...,...,...,...,...
2018-09-24,2921.830078,2923.790039,2912.629883,2919.370117,2919.370117,3372210000
2018-09-25,2921.750000,2923.949951,2913.699951,2915.560059,2915.560059,3285480000
2018-09-26,2916.979980,2931.149902,2903.280029,2905.969971,2905.969971,3388620000
2018-09-27,2911.649902,2927.219971,2909.270020,2914.000000,2914.000000,3060850000
2018-09-28,2910.030029,2920.530029,2907.500000,2913.979980,2913.979980,3432300000

In [149]:
# Filtering
sp500[ sp500['Close'] > sp500['Open'] ] 
sp500[ sp500['High'] > sp500['Close'] ] 
# mabye we only need above a threshold
# use & for logical-and, also pipe-character for logical-OR
sp500[ (sp500['Volume'] > 1.30e+09) & (sp500['Volume'] < 3.50e+09) ]

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2013-09-30,1687.260010,1687.260010,1674.989990,1681.550049,1681.550049,3308630000
2013-10-01,1682.410034,1696.550049,1682.069946,1695.000000,1695.000000,3238690000
2013-10-02,1691.900024,1693.869995,1680.339966,1693.869995,1693.869995,3148600000
2013-10-03,1692.349976,1692.349976,1670.359985,1678.660034,1678.660034,3279650000
2013-10-04,1678.790039,1691.939941,1677.329956,1690.500000,1690.500000,2880270000
...,...,...,...,...,...,...
2018-09-24,2921.830078,2923.790039,2912.629883,2919.370117,2919.370117,3372210000
2018-09-25,2921.750000,2923.949951,2913.699951,2915.560059,2915.560059,3285480000
2018-09-26,2916.979980,2931.149902,2903.280029,2905.969971,2905.969971,3388620000
2018-09-27,2911.649902,2927.219971,2909.270020,2914.000000,2914.000000,3060850000
2018-09-28,2910.030029,2920.530029,2907.500000,2913.979980,2913.979980,3432300000

In [151]:
# we may need to generate new columns containung values derived from our data
sp500['logClose'] = np.log( sp500['Close'] )
sp500

,Open,High,Low,Close,Adj Close,Volume,logClose
Date,,,,,,,
2013-09-30,1687.260010,1687.260010,1674.989990,1681.550049,1681.550049,3308630000,7.427471
2013-10-01,1682.410034,1696.550049,1682.069946,1695.000000,1695.000000,3238690000,7.435438
2013-10-02,1691.900024,1693.869995,1680.339966,1693.869995,1693.869995,3148600000,7.434771
2013-10-03,1692.349976,1692.349976,1670.359985,1678.660034,1678.660034,3279650000,7.425751
2013-10-04,1678.790039,1691.939941,1677.329956,1690.500000,1690.500000,2880270000,7.432780
...,...,...,...,...,...,...,...
2018-09-24,2921.830078,2923.790039,2912.629883,2919.370117,2919.370117,3372210000,7.979123
2018-09-25,2921.750000,2923.949951,2913.699951,2915.560059,2915.560059,3285480000,7.977817
2018-09-26,2916.979980,2931.149902,2903.280029,2905.969971,2905.969971,3388620000,7.974523
2018-09-27,2911.649902,2927.219971,2909.270020,2914.000000,2914.000000,3060850000,7.977282
2018-09-28,2910.030029,2920.530029,2907.500000,2913.979980,2913.979980,3432300000,7.977275

In [156]:
# Moving Averages
sp500['ma_1'] = sp500['Close'].shift(1)
sp500['ma_5'] = sp500['Close'].rolling( window=5, min_periods=5 ).mean()
sp500['ma_20'] = sp500['Close'].rolling( window=20, min_periods=20 ).mean()
sp500.head(40)

,Open,High,Low,Close,Adj Close,Volume,logClose,ma_1,ma_5,ma_20
Date,,,,,,,,,,
2013-09-30,1687.260010,1687.260010,1674.989990,1681.550049,1681.550049,3308630000,7.427471,NaN,NaN,NaN
2013-10-01,1682.410034,1696.550049,1682.069946,1695.000000,1695.000000,3238690000,7.435438,1681.550049,NaN,NaN
2013-10-02,1691.900024,1693.869995,1680.339966,1693.869995,1693.869995,3148600000,7.434771,1695.000000,NaN,NaN
2013-10-03,1692.349976,1692.349976,1670.359985,1678.660034,1678.660034,3279650000,7.425751,1693.869995,NaN,NaN
2013-10-04,1678.790039,1691.939941,1677.329956,1690.500000,1690.500000,2880270000,7.432780,1678.660034,1687.916016,NaN
2013-10-07,1687.150024,1687.150024,1674.699951,1676.119995,1676.119995,2678490000,7.424237,1690.500000,1686.830005,NaN
2013-10-08,1676.219971,1676.790039,1655.030029,1655.449951,1655.449951,3569230000,7.411828,1676.119995,1678.919995,NaN
2013-10-09,1656.989990,1662.469971,1646.469971,1656.400024,1656.400024,3577840000,7.412402,1655.449951,1671.426001,NaN
2013-10-10,1660.880005,1692.560059,1660.880005,1692.560059,1692.560059,3362300000,7.433997,1656.400024,1674.206006,NaN
2013-10-11,1691.089966,1703.439941,1688.520020,1703.199951,1703.199951,2944670000,7.440264,1692.560059,1676.745996,NaN
2013-10-14,1699.859985,1711.030029,1692.130005,1710.140015,1710.140015,2580580000,7.444331,1703.199951,1683.550000,NaN
2013-10-15,1709.170044,1711.569946,1695.930054,1698.060059,1698.060059,3327740000,7.437242,1710.140015,1692.072022,NaN
2013-10-16,1700.489990,1721.760010,1700.489990,1721.540039,1721.540039,3486180000,7.450975,1698.060059,1705.100025,NaN
2013-10-17,1720.170044,1733.449951,1714.119995,1733.150024,1733.150024,3453590000,7.457696,1721.540039,1713.218018,NaN
2013-10-18,1736.719971,1745.310059,1735.739990,1744.500000,1744.500000,3664890000,7.464223,1733.150024,1721.478027,NaN
2013-10-21,1745.199951,1747.790039,1740.670044,1744.660034,1744.660034,3052710000,7.464315,1744.500000,1728.382031,NaN
2013-10-22,1746.479980,1759.329956,1746.479980,1754.670044,1754.670044,3850840000,7.470036,1744.660034,1739.704028,NaN
2013-10-23,1752.270020,1752.270020,1740.500000,1746.380005,1746.380005,3713380000,7.465300,1754.670044,1744.672021,NaN
2013-10-24,1747.479980,1753.939941,1745.500000,1752.069946,1752.069946,3671700000,7.468553,1746.380005,1748.456006,NaN
2013-10-25,1756.010010,1759.819946,1752.449951,1759.770020,1759.770020,3175720000,7.472938,1752.069946,1751.510010,1709.412512
2013-10-28,1759.420044,1764.989990,1757.670044,1762.109985,1762.109985,3282300000,7.474267,1759.770020,1755.000000,1713.440509
2013-10-29,1762.930054,1772.089966,1762.930054,1771.949951,1771.949951,3358460000,7.479836,1762.109985,1758.455981,1717.288007
2013-10-30,1772.270020,1775.219971,1757.239990,1763.310059,1763.310059,3523040000,7.474948,1771.949951,1761.841992,1720.760010
2013-10-31,1763.239990,1768.530029,1755.719971,1756.540039,1756.540039,3826530000,7.471101,1763.310059,1762.736011,1724.654010
2013-11-01,1758.699951,1765.670044,1752.699951,1761.640015,1761.640015,3686290000,7.474000,1756.540039,1763.110010,1728.211011
2013-11-04,1763.400024,1768.780029,1761.560059,1767.930054,1767.930054,3194870000,7.477565,1761.640015,1764.274024,1732.801514
2013-11-05,1765.670044,1767.030029,1755.760010,1762.969971,1762.969971,3516680000,7.474755,1767.930054,1762.478028,1738.177515
2013-11-06,1765.000000,1773.739990,1764.400024,1770.489990,1770.489990,3322100000,7.479012,1762.969971,1763.914014,1743.882013
2013-11-07,1770.739990,1774.540039,1746.199951,1747.150024,1747.150024,4143200000,7.465741,1770.489990,1762.036011,1746.611511
2013-11-08,1748.369995,1770.780029,1747.630005,1770.609985,1770.609985,3837170000,7.479079,1747.150024,1763.830005,1749.982013
2013-11-11,1769.959961,1773.439941,1767.849976,1771.890015,1771.890015,2534060000,7.479802,1770.609985,1764.621997,1753.069513
2013-11-12,1769.510010,1771.780029,1762.290039,1767.689941,1767.689941,3221030000,7.477429,1771.890015,1765.565991,1756.551007
2013-11-13,1764.369995,1782.000000,1760.640015,1782.000000,1782.000000,3327480000,7.485492,1767.689941,1767.867993,1759.574005
2013-11-14,1782.750000,1791.530029,1780.219971,1790.619995,1790.619995,3139060000,7.490317,1782.000000,1776.561987,1762.447504
2013-11-15,1790.660034,1798.219971,1790.660034,1798.180054,1798.180054,3254820000,7.494530,1790.619995,1782.076001,1765.131506
2013-11-18,1798.819946,1802.329956,1788.000000,1791.530029,1791.530029,3168520000,7.490825,1798.180054,1786.004004,1767.475006
2013-11-19,1790.790039,1795.510010,1784.719971,1787.869995,1787.869995,3224450000,7.488780,1791.530029,1790.040015,1769.135004
2013-11-20,1789.589966,1795.729980,1777.229980,1781.369995,1781.369995,3109140000,7.485138,1787.869995,1789.914014,1770.884503
2013-11-21,1783.520020,1797.160034,1783.520020,1795.849976,1795.849976,3256630000,7.493234,1781.369995,1790.960010,1773.073505
2013-11-22,1797.209961,1804.839966,1794.699951,1804.760010,1804.760010,3055140000,7.498183,1795.849976,1792.276001,1775.323004